// Generated by FORME/fetch_polyfills/build_web.mjs.
const webModuleRuntime = r'''
(function(){
'use strict';
const runtimes=new Map();
function registry(id){const r=runtimes.get(id);if(!r)throw new Error('JavaScript runtime has been disposed');return r;}
function normalize(name,referrer=''){
  name=String(name);
  if(name.startsWith('.'))name=referrer.slice(0,referrer.lastIndexOf('/')+1)+name;
  const out=[];for(const part of name.split('/')){if(part==='..')out.pop();else if(part&&part!=='.')out.push(part);}return out.join('/');
}
function resolve(r,name,referrer){name=normalize(name,referrer);return r.aliases.get(name)||name;}
function link(r,name){
  if(r.records.has(name))return r.records.get(name);
  if(!r.sources.has(name))throw new TypeError('JSF module not found: '+name);
  const record={name,exports:Object.create(null),values:Object.create(null),subscribers:new Set(),dependencies:[],state:'linking',promise:null,error:null};
  Object.defineProperty(record.exports,Symbol.toStringTag,{value:'Module'});
  r.records.set(name,record);
  function publish(key,value){
    const changes=typeof key==='object'?key:{[key]:value};let changed=false;
    for(const k of Object.keys(changes)){
      if(record.allowedExports&&!record.allowedExports.has(k))continue;
      if(!Object.hasOwn(record.values,k)){
        Object.defineProperty(record.exports,k,{enumerable:true,configurable:true,get:()=>record.values[k]});changed=true;
      }
      if(!Object.is(record.values[k],changes[k]))changed=true;
      record.values[k]=changes[k];
    }
    if(changed)for(const setter of record.subscribers)setter(record.exports);
    return value;
  }
  try{
    let registration;
    record.metadata=__jsfCompiler.compile(r.sources.get(name),name||'<module>');
    r.global.Function('System',record.metadata.code)({register(deps,declare){registration={deps,declare};}});
    if(!registration)throw new TypeError('Module compilation did not produce a registration');
    const declaration=registration.declare(publish,{
      id:name,meta:{url:'jsf-module:///'+name},
      import:(specifier,options)=>{if(options!==undefined)throw new TypeError('Import attributes are not supported');return importModule(r,specifier,name);}
    });
    record.execute=declaration.execute;
    record.resolve=specifier=>r.records.get(resolve(r,specifier,name));
    for(let i=0;i<registration.deps.length;i++){
      const dep=link(r,resolve(r,registration.deps[i],name));
      record.dependencies.push(dep);
      const setter=declaration.setters[i];
      if(setter){dep.subscribers.add(setter);setter(dep.exports);}
    }
    record.state='linked';
    return record;
  }catch(error){record.state='failed';record.error=error;throw error;}
}
function exportedBinding(record,name,seen=new Set()){
  const key=JSON.stringify([record.name,name]);
  if(seen.has(key))return new Set();
  const path=new Set(seen);path.add(key);
  const own=record.metadata.bindings[name];
  if(own){
    if(own.local)return new Set([JSON.stringify([record.name,own.local])]);
    const dependency=record.resolve(own.source);
    return own.name==='*'?new Set([JSON.stringify([dependency.name,'*namespace*'])]):exportedBinding(dependency,own.name,path);
  }
  const found=new Set();
  if(name!=='default')for(const star of record.metadata.stars)for(const binding of exportedBinding(record.resolve(star),name,path))found.add(binding);
  return found;
}
function exportNames(record,seen=new Set()){
  if(seen.has(record))return new Set();seen.add(record);
  const names=new Set(Object.keys(record.metadata.bindings));
  for(const star of record.metadata.stars)for(const name of exportNames(record.resolve(star),seen))if(name!=='default')names.add(name);
  return names;
}
function validateGraph(record,seen=new Set()){
  if(seen.has(record))return;seen.add(record);
  if(record.state==='failed')throw record.error;
  for(const dep of record.dependencies)validateGraph(dep,seen);
  if(record.validated)return;
  try{
    for(const dependency of record.metadata.imports)for(const name of dependency.names){
      if(exportedBinding(record.resolve(dependency.source),name).size!==1)throw new SyntaxError('Missing or ambiguous export "'+name+'" in "'+dependency.source+'"');
    }
    record.allowedExports=new Set([...exportNames(record)].filter(name=>exportedBinding(record,name).size===1));
    for(const name of Object.keys(record.exports))if(!record.allowedExports.has(name)){delete record.exports[name];delete record.values[name];}
    record.validated=true;
  }catch(error){record.state='failed';record.error=error;throw error;}
}
function executeSync(record){
  if(record.state==='failed')throw record.error;
  if(record.state==='done'||record.state==='executing')return record.exports;
  if(record.state==='async'||record.execute.constructor.name==='AsyncFunction')throw new TypeError('This module requires evalAsync because it uses top-level await');
  record.state='executing';
  try{
    for(const dep of record.dependencies)executeSync(dep);
    const result=record.execute();
    if(result&&typeof result.then==='function'){
      record.state='async';record.promise=Promise.resolve(result).then(()=>{record.state='done';return record.exports;},error=>{record.state='failed';record.error=error;throw error;});
      record.promise.catch(()=>{});
      throw new TypeError('This module requires evalAsync because it uses top-level await');
    }
    record.state='done';return record.exports;
  }catch(error){if(record.state!=='async'){record.state='failed';record.error=error;}throw error;}
}
function ensureSync(record,seen=new Set()){
  if(seen.has(record)||record.state==='done')return;seen.add(record);
  if(record.state==='failed')throw record.error;
  if(record.state==='async'||record.execute.constructor.name==='AsyncFunction')throw new TypeError('This module requires evalAsync because it uses top-level await');
  for(const dep of record.dependencies)ensureSync(dep,seen);
}
function loadSync(record){validateGraph(record);ensureSync(record);return executeSync(record);}
function executeAsync(record,ancestors=new Set()){
  if(record.state==='failed')return Promise.reject(record.error);
  if(record.state==='done'||ancestors.has(record))return Promise.resolve(record.exports);
  if(record.promise)return record.promise;
  const path=new Set(ancestors);path.add(record);
  // Defer execution until the shared promise is visible to concurrent imports.
  record.promise=Promise.resolve().then(async()=>{
    record.state='async';
    for(const dep of record.dependencies)await executeAsync(dep,path);
    await record.execute();record.state='done';return record.exports;
  }).catch(error=>{record.state='failed';record.error=error;throw error;});
  return record.promise;
}
async function importModule(r,specifier,referrer){
  if(r.disposed)throw new Error('JavaScript runtime has been disposed');
  const record=link(r,resolve(r,specifier,referrer));validateGraph(record);return executeAsync(record);
}
function rewriteImports(source,id,filename){
  if(!source.includes('import'))return source;
  const replacement='globalThis.__jsfImport.bind(null,'+JSON.stringify(filename)+')';
  for(const index of __jsfCompiler.imports(source))source=source.slice(0,index)+replacement+source.slice(index+6);
  return source;
}
globalThis.__jsfInstallDiagnostics=function(realm,log,rejection,failure){
  if(log)realm.console=Object.fromEntries(['log','info','debug','warn','error'].map(level=>[level,(...args)=>log(level,args)]));
  if(rejection)realm.addEventListener('unhandledrejection',event=>{event.preventDefault();rejection(event.reason);});
  if(failure)realm.addEventListener('error',event=>{event.preventDefault();failure(event.error||new realm.Error(event.message));});
};
globalThis.__jsfCreateRealm=function(id){
  const frame=document.createElement('iframe');frame.style.display='none';frame.setAttribute('aria-hidden','true');document.documentElement.appendChild(frame);
  const r={frame,global:frame.contentWindow,sources:new Map(),aliases:new Map(),records:new Map(),nextEval:1,disposed:false};
  runtimes.set(id,r);
  Object.defineProperty(r.global,'__jsfImport',{value:(referrer,specifier,options)=>{if(options!==undefined)throw new TypeError('Import attributes are not supported');return importModule(r,specifier,referrer);}});
  return r.global;
};
globalThis.__jsfEval=(id,code,filename)=>registry(id).global.eval(rewriteImports(String(code),id,filename));
function evaluationRecord(id,code,filename){const r=registry(id);const name=String(filename||'<eval>')+'#eval-'+r.nextEval++;r.sources.set(name,String(code));return link(r,name);}
globalThis.__jsfModuleEval=(id,code,filename)=>loadSync(evaluationRecord(id,code,filename));
globalThis.__jsfModuleEvalAsync=(id,code,filename)=>{const record=evaluationRecord(id,code,filename);validateGraph(record);return executeAsync(record);};
globalThis.__jsfModuleLoad=(id,name)=>loadSync(link(registry(id),resolve(registry(id),name,'')));
globalThis.__jsfModuleRegister=(id,name,source)=>registry(id).sources.set(normalize(name),String(source));
globalThis.__jsfModuleAlias=(id,name,resolved)=>registry(id).aliases.set(normalize(name),normalize(resolved));
globalThis.__jsfModuleClear=id=>{const r=registry(id);r.sources.clear();r.aliases.clear();};
globalThis.__jsfModuleDispose=id=>{const r=runtimes.get(id);if(!r)return;r.disposed=true;r.global.__jsfDisposed=true;r.frame.remove();r.records.clear();r.sources.clear();r.aliases.clear();runtimes.delete(id);};
})();

''';
